<a href="https://colab.research.google.com/github/ZakyGIT2028/Scientific-Computing-LAB/blob/main/SC_sesi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
import time

In [ ]:
print(time.ctime())

Thu Feb  6 04:41:34 2025


In [ ]:
z= "Hello"
y= 20
c= 30.9
f= ["apple", "banana"]


print(z,y,c,f)

Hello 20 30.9 ['apple', 'banana']


In [ ]:
o= int(1)
y= int(2.8)
z= int("3")
j= str(20)

print(o,y,z,j)

1 2 3 20


In [ ]:
a= "Hello"
b= " World"

c= a+b

print(c)

Hello World


In [ ]:
a = "Hello World"
print(a[1])

print(len(a))

e
11


In [ ]:
#slicing

b= "BINUS Univ"
print(b[2:5])

c= "BINUS Univ"
print(c[2:])

d= "BINUS Univ"
print(c[:5])

NUS
NUS Univ
BINUS


In [ ]:
a= "Hello"
print(a.upper())

b= "World"
print(b.lower())

c= "Hello"
print(a.replace("H", "L"))

HELLO
world
Lello


In [ ]:
nama= "sam"
x= 19
nama= "sam"
x= 19
string= "Nama saya {} umur {}"

print(string.format(nama, x))

Nama saya sam umur 19


In [ ]:
nama= "Grace"

for i in enumerate(nama):
  print(i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan(a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a=b")

In [ ]:
perbandingan(4,5)

a kurang dari b


In [ ]:
i=1
while i<6:
  print(i)
  i +=1

1
2
3
4
5


In [ ]:
i=3
for i in range(0,6):
  print(i)

0
1
2
3
4
5


In [ ]:
i=1
for i in range(2,6):
  print(i)

2
3
4
5


In [ ]:

i=1
for i in range(2,41):
  if i%2:
    print(i, "ganjil")
  else:
    print(i, "genap")

2 genap
3 ganjil
4 genap
5 ganjil
6 genap
7 ganjil
8 genap
9 ganjil
10 genap
11 ganjil
12 genap
13 ganjil
14 genap
15 ganjil
16 genap
17 ganjil
18 genap
19 ganjil
20 genap
21 ganjil
22 genap
23 ganjil
24 genap
25 ganjil
26 genap
27 ganjil
28 genap
29 ganjil
30 genap
31 ganjil
32 genap
33 ganjil
34 genap
35 ganjil
36 genap
37 ganjil
38 genap
39 ganjil
40 genap


In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [3, 6, 7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
import numpy as np

y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [ ]:
print(x+y)

[[ 2  4  6]
 [ 4  8 10]]


In [ ]:
import numpy as np

data = np.array([[10,9,8,7,6,5]])

print("Rata-rata:", np.mean(data))
print("Median:", np.median(data))
print("Standar Deviasi:", np.std(data))
import numpy as np

data = np.array([[10,9,8,7,6,5]])

print("Rata-rata:", np.mean(data))
print("Median:", np.median(data))
print("Standar Deviasi:", np.std(data))
print("Maksimus:", np.max(data))
print("Minimun:", np.min(data))
print("Maksimus:", np.max(data))
print("Minimun:", np.min(data))

Rata-rata: 7.5
Median: 7.5
Standar Deviasi: 1.707825127659933
Rata-rata: 7.5
Median: 7.5
Standar Deviasi: 1.707825127659933
Maksimus: 10
Minimun: 5
Maksimus: 10
Minimun: 5


In [6]:
def calculate(uas, uts, asg):
    return 0.5 * uas + 0.3 * uts + 0.2 * asg

def grading(total):
    if total >= 85:
        return 'A'
    elif total >= 80:
        return 'A-'
    elif total >= 75:
        return 'B+'
    elif total >= 70:
        return 'B'
    elif total >= 65:
        return 'B-'
    elif total >= 60:
        return 'C'
    elif total >= 55:
        return 'D'
    elif total >= 11:
        return 'E'
    else:
        return 'F'

def get_valid_score(prompt):
    while True:
        try:
            value = float(input(prompt))
            if 0 <= value <= 100:
                return value
            else:
                print("Nilai harus antara 0 dan 100. Coba lagi.")
        except ValueError:
            print("Input tidak valid. Masukkan angka desimal.")


username = input("Masukkan username anda : ")
while True:
    password = input("Masukkan password anda : ")
    if password == "Admin123":
        print(f"Login Berhasil, Selamat datang {username}")
        break
    else:
        print("Password salah. Coba lagi.")


nama = input("Masukkan nama siswa : ")
uas = get_valid_score("Masukkan Nilai UAS : ")
uts = get_valid_score("Masukkan Nilai UTS : ")
asg = get_valid_score("Masukkan Nilai Assignment : ")

nilai_akhir = calculate(uas, uts, asg)
grade = grading(nilai_akhir)


print("\n===========================")
print(f"Hasil perolehan nilai {nama}")
print(f"Final Score: {nilai_akhir:.1f}")
print(f"Grade: {grade}")
print("===========================")

Masukkan username anda : Kirin
Masukkan password anda : Admin123
Login Berhasil, Selamat datang Kirin
Masukkan nama siswa : K
Masukkan Nilai UAS : 50
Masukkan Nilai UTS : 50
Masukkan Nilai Assignment : 50

Hasil perolehan nilai K
Final Score: 50.0
Grade: E
